### ISSUE TITLE
System folder compatibility

### ISSUE THREAD

**Issue by FerMod** [cs-ehu/Ejemplo#9]
There is a compatibility issue with the folder hierarchy, between the Windows and the Unix systems.

Affected folder: [UNE157801](https://github.com/cs-ehu/Ejemplo/tree/36f2cf1783d8a7d8138aa06540a7b3237d4d8a7b/UNE157801).

**Comment by jiptohej** [comment]
No se permiten directorios finalizados por puntos suspensivos.
